version: '3.4'

services:
  php-fpm:
    build:
      context: .
      target: products_php
    volumes:
      - .:/var/www/application
    ports:
      - "9001:9000"
    networks:
      - product-ms

  nginx:
    build:
      context: .
      target: products_nginx
    ports:
      - "81:80"
    hostname: products.local
    networks:
      - product-ms

  mysql:
    image: mariadb:10.6
    container_name: products_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: products_db
      MYSQL_USER: root
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: dbpassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - product-ms

networks:
  product-ms:
    driver: bridge
