version: '3.4'

services:
  php-fpm:
    restart: unless-stopped
    build:
      context: .
      target: he_uk_php
    volumes:
      - .:/var/www/application
    ports:
      - "9004:9000"
    networks:
      - he_uk

  nginx:
    build:
      context: .
      target: he_uk_nginx
    ports:
      - "84:80"
    hostname: products.local
    networks:
      - he_uk

  mysql:
    image: mariadb:10.6
    container_name: he_uk_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: he_uk_db
      MYSQL_USER: root
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: dbpassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - he_uk

networks:
  he_uk:
    driver: bridge
